services:
    whoami:
        image: "traefik/whoami"
        container_name: "simple-service"
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)||PathPrefix(`/who`)"
            - "traefik.http.routers.whoami.entrypoints=web"

networks:
    proxy:
        external: true


#curl -H "Host:whoami.localhost" localhost
#curl localhost/who