services:
    db:
        image: mysql:5.7
        #volumes:
            #- ./wp:/var/lib/mysql
        restart: always
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
 
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        networks:
            - proxy
            - database
        #volumes: 
            #- ./wp_content:/var/www/html/wp-content/
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.wp.rule=Host(`wp.localhost`)||PathPrefix(`/`)"
            - "traefik.http.middlewares.wp.stripprefix.prefixes=/"
            - "traefik.http.routers.wp.middlewares=wp@docker"
            - "traefik.http.routers.wp.entrypoints=web"
            
            #- "traefik.http.routers.wp.entrypoints=websecure"

            #- "traefik.http.routers.wp.rule=Host(`wp.dominio.pt`)"

            #- "traefik.http.routers.wp.tls=true"
            #- "traefik.http.routers.wp.tls.certresolver=le"


networks:
    proxy:
        external: true
    database:
        driver: bridge
