ui:
    image: organization/vtvmgmt-vfg-opsmgmtui:latest
    labels:
        - traefik.http.routers.ui.tls=true
        - traefik.http.middlewares.uimiddle.stripprefix.prefixes=/ui
        - traefik.http.routers.ui.rule=PathPrefix(`/ui`)
        - traefik.http.routers.ui.middlewares=uimiddle@docker
